name: example workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  number: 200
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Take photo of github.com
        uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
        with:
          url: https://github.com